name: heart_beat_monitor
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  camera: ^0.10.0+4
  charts_flutter_new: ^0.12.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.61.0
  flutter:
    sdk: flutter
  get: ^4.6.5
  path: ^1.8.2
  shared_preferences: ^2.0.15
  sqflite: ^2.2.0+3
  url_launcher: ^6.1.7
  wakelock: ^0.6.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: '#FFFFFF'
  image: assets/logo.png

flutter:
  uses-material-design: true
  fonts:
    - family: Changa
      fonts:
        - asset: fonts/Changa-ExtraLight.ttf
          weight: 200
        - asset: fonts/Changa-Light.ttf
          weight: 300
        - asset: fonts/Changa-Regular.ttf
          weight: 400
        - asset: fonts/Changa-Medium.ttf
          weight: 500
        - asset: fonts/Changa-SemiBold.ttf
          weight: 600
        - asset: fonts/Changa-Bold.ttf
          weight: 700
        - asset: fonts/Changa-ExtraBold.ttf
          weight: 800
